import fs from "node:fs/promises";
import fsSync from "node:fs";
import path from "node:path";
import os from "node:os";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const COMPONENTS = Object.freeze({ PANEL:"orbitfs_panel", MCP:"orbitfs_mcp", WORKSPACES:"orbitfs_workspaces", SORTER:"orbitfs_sorter" });
const ALL_COMPONENTS=Object.values(COMPONENTS), COMPONENT_SET=new Set(ALL_COMPONENTS);
export function isLicenseEnforced(){ return !(process.env.NODE_ENV==="development" && process.env.ORBITFS_DEV_LICENSE_BYPASS==="true"); }
function licenseDirectory(){const configured=String(process.env.ORBITFS_LICENSE_DIR||"").trim();if(configured)return configured;return path.join(process.env.ProgramData||process.env.PROGRAMDATA||path.join(os.homedir(),".orbitfs"),"OrbitFS");}
const installationPath=()=>path.join(licenseDirectory(),"installation.json"), cachePath=()=>path.join(licenseDirectory(),"license.json"), keyPath=()=>path.join(licenseDirectory(),"license-key.json");
const refreshMs=()=>Math.max(60000,Number(process.env.ORBITFS_LICENSE_REFRESH_MINUTES||180)*60000);
const signalPollMs=()=>Math.max(60000,Number(process.env.ORBITFS_LICENSE_SIGNAL_MINUTES||1)*60000);
function requestedComponents(value=ALL_COMPONENTS){const input=Array.isArray(value)?value:[value];return [...new Set(input.filter(x=>COMPONENT_SET.has(x)))];}
async function readJson(filepath){try{return JSON.parse(await fs.readFile(filepath,"utf8"));}catch{return null;}}
async function writeJsonAtomic(filepath,value){await fs.mkdir(path.dirname(filepath),{recursive:true});const temporary=`${filepath}.${process.pid}.tmp`;await fs.writeFile(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");await fs.rename(temporary,filepath);await fs.chmod(filepath,0o600).catch(()=>{});}
export async function ensureInstallationIdentity(){const current=await readJson(installationPath());if(current?.installationId)return current;const created={installationId:`ofs-${crypto.randomUUID()}`,createdAt:new Date().toISOString()};await writeJsonAtomic(installationPath(),created);return created;}
const keyHint=value=>{const clean=String(value||"").trim();return clean.length>4?`****${clean.slice(-4)}`:"****";};
async function storedLicenseKey(){return String((await readJson(keyPath()))?.licenseKey||process.env.ORBITFS_LICENSE_KEY||"").trim();}
async function saveLicenseKey(licenseKey){await writeJsonAtomic(keyPath(),{licenseKey:String(licenseKey).trim(),keyHint:keyHint(licenseKey),savedAt:new Date().toISOString()});}
function providerBase(){return String(process.env.ORBITFS_LICENSE_API_URL||process.env.ORBITFS_LICENSE_URL||"https://license.incendiarynetworks.cc").trim().replace(/\/+$/,"");}
function providerConfig(){const exact=String(process.env.ORBITFS_LICENSE_VALIDATE_URL||"").trim();const route=String(process.env.ORBITFS_LICENSE_VALIDATE_PATH||"/api/license/validate").trim();return {url:exact||`${providerBase()}${route.startsWith("/")?route:`/${route}`}`,token:String(process.env.ORBITFS_LICENSE_API_TOKEN||"").trim()};}
function publicKey(){const inline=String(process.env.ORBITFS_ENTITLEMENT_PUBLIC_KEY||"").replace(/\\n/g,"\n").trim();if(inline)return inline;const configured=String(process.env.ORBITFS_ENTITLEMENT_PUBLIC_KEY_PATH||"").trim();const filepath=configured||path.join(__dirname,"entitlement-public.pem");if(!fsSync.existsSync(filepath))throw Object.assign(new Error("Entitlement public key is missing"),{code:"LICENSE_PUBLIC_KEY_MISSING"});return fsSync.readFileSync(filepath,"utf8");}
function verifyEntitlement(token,installationId,{allowGrace=false}={}){const parts=String(token||"").split(".");if(parts.length!==3)throw Object.assign(new Error("Invalid signed entitlement"),{code:"LICENSE_SIGNATURE_INVALID"});const [h,p,s]=parts;const header=JSON.parse(Buffer.from(h,"base64url"));if(header.alg!=="RS256")throw new Error("Unsupported entitlement algorithm");if(!crypto.verify("RSA-SHA256",Buffer.from(`${h}.${p}`),publicKey(),Buffer.from(s,"base64url")))throw Object.assign(new Error("Entitlement signature check failed"),{code:"LICENSE_SIGNATURE_INVALID"});const payload=JSON.parse(Buffer.from(p,"base64url"));const now=Math.floor(Date.now()/1000), deadline=allowGrace?payload.graceUntil:payload.exp;if(payload.iss!=="license.incendiarynetworks.cc"||payload.aud!=="orbitfs-runtime"||!deadline||now>deadline)throw Object.assign(new Error("Signed entitlement expired or invalid"),{code:"LICENSE_ENTITLEMENT_EXPIRED"});if(payload.installationId!==installationId)throw Object.assign(new Error("Entitlement belongs to another installation"),{code:"LICENSE_INSTALLATION_MISMATCH"});return payload;}
async function callProvider({licenseKey,components,activate}){const cleanKey=String(licenseKey||"").trim();if(!cleanKey)throw Object.assign(new Error("Licence key is required"),{code:"LICENSE_KEY_REQUIRED",status:400});const installation=await ensureInstallationIdentity(),{url,token}=providerConfig();const headers={"Content-Type":"application/json"};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(url,{method:"POST",headers,body:JSON.stringify({licenseKey:cleanKey,installationId:installation.installationId,components:requestedComponents(components),activate:activate===true}),signal:AbortSignal.timeout(Number(process.env.ORBITFS_LICENSE_TIMEOUT_MS||8000))});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.error||body.message||`Licence API returned ${response.status}`),{code:body.code||"LICENSE_PROVIDER_ERROR",status:response.status<500?response.status:503});if(!body.entitlement)throw Object.assign(new Error("Licence API returned no signed entitlement"),{code:"LICENSE_UNSIGNED_RESPONSE",status:503});return {...verifyEntitlement(body.entitlement,installation.installationId),entitlement:body.entitlement};}
async function persist(result,source,licenseKey){const cache={entitlement:result.entitlement,keyHint:keyHint(licenseKey),source,lastCheckedAt:new Date().toISOString()};await writeJsonAtomic(cachePath(),cache);const { entitlement, ...publicResult } = result; return {...publicResult,enforcement:true,keyHint:cache.keyHint,source,lastCheckedAt:cache.lastCheckedAt};}
async function verifiedCache(cache,{allowGrace=false}={}){if(!cache?.entitlement)return null;const installation=await ensureInstallationIdentity();const payload=verifyEntitlement(cache.entitlement,installation.installationId,{allowGrace});return {...payload,enforcement:true,keyHint:cache.keyHint||null,source:cache.source||"cache",lastCheckedAt:cache.lastCheckedAt||null};}
function bypassSummary(){return {valid:true,enforcement:false,reason:"development_bypass",components:Object.fromEntries(ALL_COMPONENTS.map(c=>[c,{state:"development",allowed:true,lockedToThisInstallation:true,reason:null}]))};}
export async function activateComponents(licenseKey,components=ALL_COMPONENTS){if(!isLicenseEnforced())return bypassSummary();const cleanKey=String(licenseKey||await storedLicenseKey()).trim(),requested=requestedComponents(components);const result=await callProvider({licenseKey:cleanKey,components:requested,activate:true});const denied=requested.filter(c=>{const i=result.components?.[c];return i?.state!=="locked"||i?.allowed!==true||i?.lockedToThisInstallation!==true;});if(!result.valid||denied.length)throw Object.assign(new Error(`Licence does not allow ${denied.join(", ")||"this installation"}`),{code:result.reason||"LICENSE_COMPONENT_DENIED",status:403,license:result});await saveLicenseKey(cleanKey);return persist(result,"activation",cleanKey);}
export async function getLicenseSummary({refresh=false}={}){if(!isLicenseEnforced())return bypassSummary();const licenseKey=await storedLicenseKey();if(!licenseKey)return {valid:false,enforcement:true,reason:"not_activated",components:{}};const cache=await readJson(cachePath());if(!refresh&&cache?.lastCheckedAt&&Date.now()-Date.parse(cache.lastCheckedAt)<refreshMs()){try{const verified=await verifiedCache(cache);if(verified)return verified;}catch{}}
try{return await persist(await callProvider({licenseKey,components:ALL_COMPONENTS,activate:false}),"refresh",licenseKey);}catch(error){try{const fallback=await verifiedCache(cache,{allowGrace:true});if(fallback?.valid)return {...fallback,offlineGrace:true,refreshError:error.message};}catch{}return {valid:false,enforcement:true,reason:error.code||"provider_unavailable",refreshError:error.message,components:{}};}}
export async function getComponentStatus(component,options={}){if(!COMPONENT_SET.has(component))throw new Error(`Unknown licence component: ${component}`);const summary=await getLicenseSummary(options),item=summary.components?.[component]||{state:"blocked",allowed:false,lockedToThisInstallation:false,reason:summary.reason||"not_included"};return {...item,component,licensed:summary.enforcement===false||(summary.valid===true&&item.state==="locked"&&item.allowed===true&&item.lockedToThisInstallation===true),valid:summary.valid===true,enforcement:summary.enforcement!==false,offlineGrace:summary.offlineGrace===true,keyHint:summary.keyHint||null,lastCheckedAt:summary.lastCheckedAt||null,installationId:summary.installationId||null};}
export async function assertComponentLicensed(component,options={}){const status=await getComponentStatus(component,options);if(status.licensed)return status;throw Object.assign(new Error(`${component} licence is blocked, suspended, expired or not activated`),{code:"LICENSE_REQUIRED",status:403,license:status});}
export function licenseGuard(component,{readOnlyOnFailure=false}={}){return async(req,res,next)=>{try{await assertComponentLicensed(component);next();}catch(error){if(readOnlyOnFailure&&["GET","HEAD","OPTIONS"].includes(req.method)){req.licenseRestricted=true;return next();}res.status(error.status||403).json({error:error.message,code:error.code||"LICENSE_REQUIRED",license:error.license||null,restricted:true});}};}
let heartbeat=null,signal=null,lastRevision=null;export function startLicenseHeartbeat({onUpdate,onError}={}){if(heartbeat||signal)return()=>{};const check=async()=>{if(!isLicenseEnforced())return;try{onUpdate?.(await getLicenseSummary({refresh:true}));}catch(e){onError?.(e);}};const checkSignal=async()=>{try{const r=await fetch(`${providerBase()}/api/license/revision`,{signal:AbortSignal.timeout(8000)});if(!r.ok)return;const revision=(await r.json()).revision;if(lastRevision&&revision!==lastRevision)await check();lastRevision=revision;}catch(e){onError?.(e);}};check();checkSignal();heartbeat=setInterval(check,refreshMs());signal=setInterval(checkSignal,signalPollMs());heartbeat.unref?.();signal.unref?.();return()=>{clearInterval(heartbeat);clearInterval(signal);heartbeat=signal=null;};}
export function getLicensePaths(){return {directory:licenseDirectory(),installation:installationPath(),cache:cachePath(),key:keyPath()};}
